import { PrismaClient } from '@prisma/client';
const db = new PrismaClient();

function getProducts() {
  return [
    {
      id: 'ipadair1',
      name: 'IPad Air',
      size: "10'1",
      price: 1500,
      description: 'iPad Air lets you immerse yourself in whatever you’re reading, watching, or creating',
      collection: 'New Collection',
      category: 'ipad',
      photo: "IPadAir.jpg",
      gallery:"IPadAir.jpg",
      quantity: 1,
      status: 'top-seller',
    },
    {
      id: 'ipadair2',
      name: 'IPad Air',
      size: "10'1",
      price: 1500,
      description: 'iPad Air lets you immerse yourself in whatever you’re reading, watching, or creating',
      collection: 'New Collection',
      category: 'ipad',
      photo: "IPadAir.jpg",
      gallery:"IPadAir.jpg",
      quantity: 1,
      status: 'top-seller',
    },
    {
      id: 'iphone11',
      name: 'IPhone 11',
      size: "5'1",
      price: 2000,
      description: 'The iPhone 11 has IPS LCD with a resolution of 1792 × 828 pixels',
      collection: 'Golden Collection',
      category: 'iphone',
      photo: "IPhone11.jpg",
      gallery:"IPhone11.jpg,IPhone11.jpg",
      quantity: 1,
      status: 'top-seller',
    },
    {
      id: 'iphone12pro1',
      name: 'IPhone 12 Pro',
      size: "6'1",
      price: 3200,
      description: 'Designed with premium materials, iPhone 12 Pro models boast a new',
      collection: 'New Collection',
      category: 'iphone',
      photo: "IPhone_12_Pro.jpg",
      gallery:"IPhone_12_Pro, IPhone_12_Pro",
      quantity: 1,
      status: 'top-seller',
    },
    {
      id: 'mavic1',
      name: 'DJI Mavic 3',
      size: "10",
      price: 3000,
      description: 'Mavic 3 Classic delivers the absolute essence of flagship imaging.',
      collection: 'New Collection',
      category: 'other',
      photo: "DJI_Mavic_3.jpg",
      gallery:"DJI_Mavic_3.jpg, DJI_Mavic_3.jpg",
      quantity: 1,
      status: 'top-seller',
    },
    {
      id: 'mavic2',
      name: 'DJI Mavic Full',
      size: "10",
      price: 5000,
      description: 'With powerful flight performance and a Hasselblad camera.',
      collection: 'New Collection',
      category: 'other',
      photo: "DJI_Mavic_Full.jpg",
      gallery:"DJI_Mavic_Full.jpg, DJI_Mavic_Full.jpg",
      quantity: 1,
      status: 'other',
    },
    {
      id: 'nintendo1',
      name: 'Nintendo Switch Console',
      size: "6'2",
      price: 2800,
      description: 'The Nintendo Switch is a hybrid video game console, consisting of a console unit, a dock, and two Joy-Con controllers.',
      collection: 'New Collection',
      category: 'other',
      photo: "Nintendo_SwitchConsole.jpg",
      gallery:"Nintendo_SwitchConsole.jpg, Nintendo_SwitchConsole.jpg",
      quantity: 1,
      status: 'top-seller',
    },
    {
      id: 'nintendo2',
      name: 'Nintendo Switch',
      size: "6'2",
      price: 3100,
      description: 'The Nintendo Switch is a hybrid video game console, consisting of a console unit, a dock, and two Joy-Con controllers.',
      collection: 'New Collection',
      category: 'other',
      photo: "Nintendo_Switch.jpg",
      gallery:"Nintendo_Switch.jpg, Nintendo_Switch.jpg",
      quantity: 1,
      status: 'top-seller',
    },
    {
      id: 'nintendo3',
      name: 'Nintendo Switch Console',
      size: "6'2",
      price: 2800,
      description: 'The Nintendo Switch is a hybrid video game console, consisting of a console unit, a dock, and two Joy-Con controllers. ',
      collection: 'New Collection',
      category: 'other',
      photo: "Nintendo_SwitchConsole.jpg",
      gallery:"Nintendo_SwitchConsole.jpg, Nintendo_SwitchConsole.jpg",
      quantity: 1,
      status: 'top-seller',
    },
    {
      id: 'promo1',
      name: 'PS 2 VR',
      size: "12'",
      price: 1300,
      description: 'Similar to the original PS VR',
      collection: 'New Collection 2024',
      category: 'other',
      photo: "PlayStation_VR2_1.jpg",
      gallery:"PlayStation_VR2_1.jpg",
      quantity: 1,
      status: 'promo',
    },{
      id: 'promo2',
      name: 'XBOX',
      size: "12'",
      price: 2000,
      description: 'Xbox, video game console.',
      collection: 'New Collection 2024',
      category: 'other',
      photo: "XBOX_1.jpg",
      gallery:"XBOX_1.jpg",
      quantity: 1,
      status: 'promo',
    },
    {
      id: 'promo3',
      name: 'PlayStation VR',
      size: "12'",
      price: 1200,
      description: 'The PlayStation VR has a 5.7 inch OLED panel.',
      collection: 'New Collection 2024',
      category: 'other',
      photo: "PlayStation_VR2_1.jpg",
      gallery:"PlayStation_VR2_1.jpg",
      quantity: 1,
      status: 'promo',
    },
    {
      id: 'ps1',
      name: 'Playstation 4',
      size: "12'",
      price: 4600,
      description: 'The console features a hardware on-the-fly zlib decompression module.',
      collection: 'Golden Collection',
      category: 'other',
      photo: "Playstation4.jpg",
      gallery:"Playstation4.jpg, Playstation4.jpg",
      quantity: 1,
      status: 'top-seller',
    },
    {
      id: 'ps2',
      name: 'Playstation 5',
      size: "12'",
      price: 5500,
      description: 'he PlayStation 5\'s main hardware features include a solid-state drive customized for high-speed data streaming.',
      collection: 'Spring Collection',
      category: 'other',
      photo: "Playstation5.jpg",
      gallery:"Playstation5.jpg",
      quantity: 1,
      status: 'new-added',
    },
    {
      id: 'ps3',
      name: 'PlayStation VR2',
      size: "10",
      price: 7800,
      description: 'Similar to the original PS VR, the new PS VR2 also features a Social Screen, which allows others to see what the player is experiencing in a 2D format on a TV screen',
      collection: 'New Collection',
      category: 'other',
      photo: "PlayStation_VR2.jpg",
      gallery:"PlayStation_VR2.jpg",
      quantity: 1,
      status: 'top-seller',
    },
    {
      id: 'ps4',
      name: 'Sony PlayStation 4 Slim.',
      size: "12'",
      price: 7600,
      description: 'The lighter and slimmer PlayStation® 4 console has a 1TB hard drive to store all your games, apps, recorded footage, and more.',
      collection: 'New Collection',
      category: 'other',
      photo: "Sony_PlayStation4_Slim.jpg",
      gallery:"Sony_PlayStation4_Slim.jpg, Sony_PlayStation4_Slim.jpg",
      quantity: 1,
      status: 'new-collection',
    },
    {
      id: 'ps5',
      name: 'PlayStation VR',
      size: "10",
      price: 5500,
      description: 'The PlayStation VR has a 5.7 inch OLED panel, with a display resolution of 1080p.',
      collection: 'New Collection',
      category: 'other',
      photo: "Sony_PlayStation_VR.jpg",
      gallery:"Sony_PlayStation4_Slim.jpg, Sony_PlayStation4_Slim.jpg",
      quantity: 1,
      status: 'top-seller',
    },
    {
      id: 'ps6',
      name: 'Playstation 4',
      size: "12'",
      price: 4500,
      description: 'The console features a hardware on-the-fly zlib decompression module.',
      collection: 'Spring Collection',
      category: 'other',
      photo: "Playstation4.jpg",
      gallery:"Playstation4.jpg",
      quantity: 1,
      status: 'new-added',
    },
    {
      id: 'xbox1',
      name: 'Microsoft XBOX',
      size: "12'",
      price: 5550,
      description: 'Xbox, video game console system created by the American company Microsoft.',
      collection: 'New Collection',
      category: 'other',
      photo: "XBOX.jpg",
      gallery:"XBOX.jpg, XBOX.jpg",
      quantity: 1,
      status: 'new-collection',
    },
  ];
}

async function seed() {
  await Promise.all(
    getProducts().map((product) => {
      return db.product.create({ data: product });
    }),
  );
}
seed();